<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "easyvote"
 *
 * Auto generated by Extension Builder 2013-09-19
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'easyvote',
	'description' => '',
	'category' => 'plugin',
	'author' => 'Lorenz Ulrich',
	'author_email' => 'lorenz.ulrich@visol.ch',
	'author_company' => 'visol digitale Dienstleistungen GmbH',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '1',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0',
			'vidi' => '',
			'routing' => '',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>