#####################
# easyvote
#####################
-
  name: 'PartyFunctions'
  uriPattern: 'partymembers/{demand}'
  defaults:
    '@package':    'Visol.Easyvote'
    '@plugin':     'Partyfunctions'
    '@controller': 'Party'
    '@action':     'listMembersByDemand'
  httpMethods: ['GET']
-
  name: 'PartyFunctions'
  uriPattern: 'partymembers'
  defaults:
    '@package':    'Visol.Easyvote'
    '@plugin':     'Partyfunctions'
    '@controller': 'Party'
    '@action':     'listMembersByDemand'
  httpMethods: ['GET']
-
  name: 'PartyMember'
  uriPattern: 'ev/{@controller}/{@action}/{object}'
  defaults:
    '@package':    'Visol.Easyvote'
    '@plugin':     'Partyfunctions'
  httpMethods: ['GET', 'POST']